services:
    lucee:
        build:
            context: ./lucee
            args:
                - LUCEE_PASSWORD=${LUCEE_PASSWORD}
        env_file:
            - env/envVars.public
            - env/envVars.private
        volumes:
            - ../:/var/www
            - ../var/log/tomcat:/usr/local/tomcat/logs
            - ../var/log/lucee/web:/opt/lucee/web/logs
            - ../var/log/lucee/server:/opt/lucee/server/lucee-server/context/logs
            - ./lucee/root_home/.bash_history:/root/.bash_history
            - ../../cfml/:/var/www/cfml/
        ports:
            - "8854:8888"
        stdin_open: true
        tty: true
        networks:
            - backend

    mariadb:
        build:
            context: ./mariadb
        env_file:
            - env/envVars.public
            - env/envVars.private
        ports:
            - "3354:3306"
        volumes:
            - mariaDbData:/var/lib/mariadb
            - ./mariadb/root_home:/root
            - ../var/log:/var/log
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - database.backend

volumes:
    mariaDbData:

networks:
    backend:
        driver: "bridge"
